### ISSUE TITLE
auth.loginCallbackFactory is undefined

### ISSUE THREAD

**Issue by PedroBorracho** [awslabs/aws-mobile-react-native-starter#33]
Hi,

I'm looking to apply the libs to my ReactNative project, but I'm facing few problems with the sign-in component: "auth.loginCallbackFactory is undefined"

I did follow the read-me and I get the error when submitting the login; 
https://github.com/awslabs/aws-mobile-react-native-starter/blob/87f558001f6260ac83bde44dc642cbe1048deff1/client/lib/Categories/Auth/Components/Examples/SignIn.js#L62

I did notice a difference in the dependencies of the lib:
> Copy lib folder from this starter app
> cp -rf ../<some-directory>/aws-react-native-native-starter/client/lib
> npm install aws-sdk react-native-aws-cognito-js react-native-prompt --save

the lib looks for a dependency on "aws-amplify-react-native",
https://github.com/awslabs/aws-mobile-react-native-starter/blob/d0e2953cfc79c362e485370eb10202c65b460853/client/lib/Categories/Auth/Components/WithAuth.js#L16

but in the readme is not listed in the dependencies (react-native-aws-cognito-js is installed instead, but I did not find any reference in code)

Thanks for your help!

**Comment by nidsharm** [comment]
Hey @PedroBorracho ,

We have recently updated the starter project to use [AWS Amplify](https://github.com/aws/aws-amplify) instead of the helper code that we had in it initially. We have updated the README instructions for integration with your app.  
Can you try integrating with AWS using the new instructions? Please let us know if you face issues with it.

Thanks,
Nidhi
